apiVersion: v1
kind: Secret
metadata:
  name: {{ include "doc-intelligence.fullname" . }}-secrets
  labels:
    {{- include "doc-intelligence.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.storageAccessKey }}
  APP_STORAGE_ACCESS_KEY: {{ .Values.secrets.storageAccessKey | quote }}
  {{- end }}
  {{- if .Values.secrets.storageSecretKey }}
  APP_STORAGE_SECRET_KEY: {{ .Values.secrets.storageSecretKey | quote }}
  {{- end }}

