{{- if and .Values.api.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "doc-intelligence.fullname" . }}
  labels:
    {{- include "doc-intelligence.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "doc-intelligence.api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}

