apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: doc-intelligence

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api-deployment.yaml
  - ocr-deployment.yaml
  - api-service.yaml
  - ocr-service.yaml
  - ingress.yaml
  - api-hpa.yaml
  - ocr-hpa.yaml
  - api-servicemonitor.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: doc-intelligence

