apiVersion: v1
kind: Service
metadata:
  name: ocr-service
  namespace: doc-intelligence
  labels:
    app.kubernetes.io/name: ocr
    app.kubernetes.io/component: ocr-service
    app.kubernetes.io/part-of: doc-intelligence
spec:
  type: ClusterIP
  selector:
    app: ocr
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
  sessionAffinity: None

